# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a75tfgg484-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_32_32_clk1_comtx
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_74_74_clk1_bar_rd1
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_64_64
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_49_49_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_129_129_clk1
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_34_34
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_256_32_clk2_comtx
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/drom_pcie_cfgspace_writemask
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_134_134_clk1_bar_rdrsp
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_64_64_clk2_comrx
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_134_134_clk2_rxfifo
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_43_43_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_32_32_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_64_64_clk1_fifocmd
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_1_1_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_134_134_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/bram_pcie_cfgspace
  } {
      E:/VIVADO2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      E:/VIVADO2023/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -include {
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_32_32_clk1_comtx
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_74_74_clk1_bar_rd1
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_64_64
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_49_49_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_129_129_clk1
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_34_34
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_256_32_clk2_comtx
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/drom_pcie_cfgspace_writemask
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_134_134_clk1_bar_rdrsp
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_64_64_clk2_comrx
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_134_134_clk2_rxfifo
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_43_43_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_32_32_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_64_64_clk1_fifocmd
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_1_1_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_134_134_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/bram_pcie_cfgspace
  } {
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src/pcileech_com.sv
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src/pcileech_fifo.sv
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src/pcileech_ft601.sv
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src/pcileech_mux.sv
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src/pcileech_pcie_a7.sv
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src/pcileech_pcie_cfg_a7.sv
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src/pcileech_pcie_tlp_a7.sv
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src/pcileech_tlps128_bar_controller.sv
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src/pcileech_tlps128_cfgspace_shadow.sv
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src/pcileech_enigma_x1_top.sv
    }
      rt::read_verilog -include {
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/src
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_32_32_clk1_comtx
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_74_74_clk1_bar_rd1
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_64_64
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_49_49_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_129_129_clk1
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_34_34
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_256_32_clk2_comtx
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/drom_pcie_cfgspace_writemask
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_134_134_clk1_bar_rdrsp
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_64_64_clk2_comrx
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_134_134_clk2_rxfifo
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_43_43_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_32_32_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_64_64_clk1_fifocmd
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_1_1_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_134_134_clk2
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr
    D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/ip/bram_pcie_cfgspace
  } {
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_32_32_clk1_comtx_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_74_74_clk1_bar_rd1_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_64_64_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_49_49_clk2_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_129_129_clk1_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_34_34_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_256_32_clk2_comtx_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/drom_pcie_cfgspace_writemask_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_134_134_clk1_bar_rdrsp_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_64_64_clk2_comrx_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_134_134_clk2_rxfifo_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_43_43_clk2_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_32_32_clk2_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_64_64_clk1_fifocmd_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_1_1_clk2_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_134_134_clk2_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/fifo_141_141_clk1_bar_wr_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/realtime/bram_pcie_cfgspace_stub.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_axi_basic_rx.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_axi_basic_rx_null_gen.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_axi_basic_rx_pipeline.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_axi_basic_top.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_axi_basic_tx.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_axi_basic_tx_pipeline.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_axi_basic_tx_thrtl_ctl.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_core_top.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_gt_common.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_gt_rx_valid_filter_7x.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_gt_top.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_gt_wrapper.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_gtp_cpllpd_ovrd.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_gtp_pipe_drp.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_gtp_pipe_rate.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_gtp_pipe_reset.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_gtx_cpllpd_ovrd.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pcie2_top.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pcie_7x.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pcie_bram_7x.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pcie_bram_top_7x.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pcie_brams_7x.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pcie_pipe_lane.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pcie_pipe_misc.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pcie_pipe_pipeline.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pcie_top.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pipe_clock.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pipe_drp.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pipe_eq.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pipe_rate.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pipe_reset.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pipe_sync.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pipe_user.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_pipe_wrapper.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_qpll_drp.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_qpll_reset.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_qpll_wrapper.v
      D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/pcileech_enigma_x1.srcs/sources_1/imports/diviner-full-emu-v2-main/pcie_7x/pcie_7x_0_rxeq_scan.v
    }
      rt::read_vhdl -lib xpm E:/VIVADO2023/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top pcileech_enigma_x1_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/PCILEECH_EMUS/V2/diviner-full-emu-v2-main/FULLCFG_VGK/.Xil/Vivado-10116-Shawk/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
